branches:
  only:
    - master
    - develop

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install libssl-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install openssl; fi

before_script:
  - git submodule update --init --recursive
  - ./bootstrap
  - ./bootstrap
  - if [ $TRAVIS_OS_NAME == linux ]; then ./configure --with-ssl --with-test; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ./configure --with-ssl=/usr/local/opt/openssl --with-test; fi

script:
  - make clean all check

notifications:
  email: false

