language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install libssl-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install openssl; fi

before_script:
  - git submodule update --init --recursive
  - ./bootstrap && ./configure --with-ssl --with-test

script: make clean all check

notifications:
  email: false

os:
  - linux
  - osx
